### ISSUE TITLE
Can't create a pull request. Don't know why. Can this one new faq be added? (Filed attached)

### ISSUE THREAD

**Issue by PeterParker2008** [AMD-OSX/AMD-OSX-FAQ#4]
[A new faq.txt](https://github.com/AMD-OSX/AMD-OSX-FAQ/files/8148207/A.new.faq.txt)

**Comment by alyxandraio** [comment]
This is just copied and pasted from the Dortania guide. This info is already in the FAQ as well.

**Comment by PeterParker2008** [comment]
kk
