### ISSUE TITLE
APU 1636:1002 Vega 7 

### ISSUE THREAD

**Issue by fr4b3lo** [AMD-OSX/AMD-OSX-FAQ#9]
Hello, first I congratulate by this incredible work. The AMD Ryzentosh don't work without this project. I buy I cheap laptop in Brazil with very good Ryzen 7 4800H 8 core ASUS M1502IA. I managed install Ventura on it that recognised the processors, battery manager, etc. But I had very difficult to config the APU 1636:1002 Renoir Vega 7. When Ii putt the kext WhateverGreen don't recognized acceleration and some apps open with very low 7mb vram.  When I use Nootedred I get acceleration, metal support, everythings good excepted the VM memory =0 that crash most of apps.  

Next post i Will send the errors.

**Comment by alyxandraio** [comment]
Please bring your issue up in the AMD OS X Discord or with the NootedRed team instead.

**Comment by fr4b3lo** [comment]
Ok
Sorry

Em seg, 18 de dez de 2023 15:20, Alyx Ferrari ***@***.***>
escreveu:
